FROM ubuntu
MAINTAINER fazel fouladi

WORKDIR /root

RUN apt update
RUN apt install wget -y
RUN wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh

RUN chmod +x openvpn-install.sh

EXPOSE 1194

CMD [ "/bin/bash","openvpn-install.sh" ]