FROM ubuntu
MAINTAINER fazel fouladi

WORKDIR /root

RUN apt update
RUN apt install wget -y
RUN wget https://git.io/vpn -O openvpn-install.sh

RUN mv openvpn-install.sh /usr/bin/openvpn-install

RUN chmod +x /usr/bin/openvpn-install


EXPOSE 1194

CMD [ "/bin/bash" ]